/**
 * Shared knobs for the sigil smoke test.
 *
 * Everything is env-driven so the same spec runs against a local docker stack
 * and against production after a deploy.
 */

export const GROUPS = ['text', 'chat', 'explainer'] as const;
export const LANGS = ['de', 'en'] as const;
export const SECTIONS = ['elements'] as const;

export type SigilGroup = (typeof GROUPS)[number];
export type SigilLang = (typeof LANGS)[number];
export type SigilSection = (typeof SECTIONS)[number];

/**
 * Group capabilities — mirrors SIGIL_GROUP_CONFIG on the server and
 * SIGIL_GROUP_CAPABILITIES in the client. Deliberately duplicated (not
 * imported) so the test asserts the expected behavior independently of the
 * app's own source of truth.
 */
export const EXPECTED_CAPABILITIES: Record<SigilGroup, { hasChat: boolean; hasPractice: boolean }> = {
  explainer: { hasChat: true, hasPractice: true },
  chat: { hasChat: true, hasPractice: false },
  text: { hasChat: false, hasPractice: false },
};

/** The study has a single learning round, so there is only one section to test. */
export const SECTION: SigilSection = 'elements';

/**
 * How long the explainer group may take to show the practice ("Weiter") button.
 * The practice quiz is generated by the LLM in the background after the session
 * is created, so this is the slowest assertion in the suite.
 */
export const PRACTICE_TIMEOUT_MS = Number(process.env.E2E_PRACTICE_TIMEOUT_MS ?? 120_000);

/**
 * Grace period before asserting that something is *absent* (chat for the text
 * group, practice button for text/chat). Without it we'd assert on an element
 * that simply hasn't rendered yet and pass for the wrong reason.
 */
export const ABSENCE_GRACE_MS = Number(process.env.E2E_ABSENCE_GRACE_MS ?? 8_000);

/** Soft access-gate token (SITE_ACCESS_TOKEN); unset locally. */
export const ACCESS_TOKEN = process.env.E2E_ACCESS_TOKEN ?? '';

/**
 * Shared secret (server-side E2E_TEST_TOKEN) sent with every request the
 * browser makes. The server stores sessions created with it as
 * `is_test_run = true`, so a run that crashes before cleanup still leaves
 * clearly identifiable rows behind instead of silent noise in the study data.
 */
export const TEST_TOKEN = process.env.E2E_TEST_TOKEN ?? '';
export const TEST_TOKEN_HEADER = 'x-e2e-test-token';

/**
 * Delete every session the run created once the test finishes (default).
 * Set E2E_CLEANUP=0 to keep them around for debugging.
 */
export const CLEANUP_ENABLED = process.env.E2E_CLEANUP !== '0';

/**
 * A distinctive heading from the learning material for each section/language.
 * Seeing it proves the markdown from server/src/modules/sigil/content/ actually
 * reached the browser — not just that the page frame rendered.
 */
export const MATERIAL_HEADING: Record<SigilSection, Record<SigilLang, string>> = {
  elements: { de: '1. Bundeslandshintergrund', en: '1. State Background' },
};

/** Builds the study URL exactly the way the survey embeds it. */
export function sigilUrl(group: SigilGroup, section: SigilSection, lang: SigilLang): string {
  const params = new URLSearchParams({ lang });
  if (ACCESS_TOKEN) params.set('token', ACCESS_TOKEN);
  return `/sigil/${group}/${section}?${params.toString()}`;
}
